### ISSUE TITLE
Support below 6.0？

### ISSUE THREAD

**Issue by aviraxp** [apsun/NoOverlayWarning#2]
As far as I know, we only have to change the package name.

**Comment by apsun** [comment]
Sure. For the package `Install` button, right? Looks like it was added in Android 4.0 https://github.com/android/platform_packages_apps_packageinstaller/commit/8c6dfd8b11954ac6ab7a85b3db45cbcc7e9d8b42#diff-fdd4a692599146fd2cd173ee4c86b59d

**Comment by aviraxp** [comment]
That would be nice.

From 6.0 the package name change to com.google.android.packageinstaller rather than  com.android.packageinstaller, right?

**Comment by apsun** [comment]
Yes, I think so (Let me see if I can find a 5.x phone to test)

New hook can be on `MotionEvent#getFlags()`, just have to clear the `MotionEvent.FLAG_WINDOW_IS_OBSCURED` bit

```
XposedHelpers.findAndHookMethod(MotionEvent.class, "getFlags", new XC_MethodHook() {
    @Override
    protected void afterHookedMethod(MethodHookParam param) throws Throwable {
        int flags = (Integer)param.getResult();
        flags &= ~MotionEvent.FLAG_WINDOW_IS_OBSCURED;
        param.setResult(flags);
    }
});
```

**Comment by aviraxp** [comment]
Nice. Compile a test build and let coolapkers test?

**Comment by aviraxp** [comment]
By the way, will you support some unstandard rom?

Such as Mokee, which changes it to com.mokee.packageinstaller.

https://github.com/MoKee/android_packages_apps_PackageInstaller/tree/mkl-mr1

**Comment by apsun** [comment]
Sure. Actually this new method works on any app (it is the SuperSU fix I mentioned), but I think I will limit it to the package installer unless someone has a reason to use it outside of that.
