### ISSUE TITLE
huawei emui 4.01 android 6.01 not working

### ISSUE THREAD

**Issue by daniel-lo** [apsun/NoOverlayWarning#4]
Hi folks, I was really hoping for such an xposed module so thanks for the effort so far. I run "Button Saviour" and loads of apps I use/install always want me to disable it it due to it overlaying stuff .. I hoped to get rid of all those requests and stop having to toggle it off/on all the time .. but it doesn't do the trick. Anything I missed .. is this not what it was intended for? Cheers

**Comment by aviraxp** [comment]
As you can see into the code, this app only hooks packageinstaller.

```
    "com.android.packageinstaller",        // Pre-Marshmallow
    "com.google.android.packageinstaller", // Marshmallow
    "com.mokee.packageinstaller"           // MoKee`
```

You can add your own package name and compile it yourself.

**Comment by daniel-lo** [comment]
Regrettably I am not a programmer. A version which generally disables that mechanism would be very appealing.

**Comment by aviraxp** [comment]
I know nothing about programming either, but I think what I have to do is hook all packages, that seems easy as the code reads like natural language. I have built a version myself and if @apsun permits, I can send you.

**Comment by daniel-lo** [comment]
Glad to try :-)

**Comment by apsun** [comment]
@aviraxp Of course, it's MIT licensed after all ;-)

@daniel-lo The hooking method does work with any app, so you can remove the package check in the beginning of `handleLoadPackage` and overlay detection will be disabled in every app. I intentionally only included the package installer apps, since those are the ones responsible for APK installation and permission request dialogs.

Maybe you would like this to be blacklist and not whitelist based? As in, disable overlay detection in everything except e.g. SuperSU (which would be dangerous)

**Comment by aviraxp** [comment]
I just noticed that. According to you, I think the way I refractor the code is right.

https://github.com/aviraxp/NoOverlayWarning/raw/patch-2/release.apk

Tested on my Oneplus2 with Paranoid Android 6.0.2.

**Comment by daniel-lo** [comment]
Generally I think the way Google has implemented this security check is inverse to how it should be (at least the way I experience it in my Huawei). Instead of having to guess which app might be the one that has to be turned off (this is a hassle) it should request the user if the app - asking for permission - is allowed to be overlayed. I hope Google changes this at some point in time. Until then I will gladly live without this security because I step into this regularly and I really like using my overlaying tools.

@aviraxp I will test now :-)

**Comment by daniel-lo** [comment]
At first I though it wouldn't work but I obviously didn't wait long enough after I rebooted. And then - like magic - the overlay reqest was gone :-) Wow .. will see how it goes the next days and report back .. but for now .. THANKS A LOT!
Will you make another branch for this patch .. or will it bekome an option? Otherwise I think there may be some confusion for users.

**Comment by daniel-lo** [comment]
I just installed Duo and overlay message stops me from giving it camera access permission. So regrettably it's not solved yet.

**Comment by apsun** [comment]
@daniel-lo Care to post your Xposed logs? It seems this module is failing on quite a few devices and I can't figure out why (or rather, nobody has been willing to post logs)

**Comment by daniel-lo** [comment]
I don't like to make logs public but I would email you a link .. but my logs are empty (no idea why) .. at least in the xposed logs window. Would a catlog do?

**Comment by daniel-lo** [comment]
Just sent a logcat via email .. hope it helps

**Comment by aviraxp** [comment]
If this moudle works, we can see in logcat like
`08-21 00:06:48.052 I/NoOverlayWarning(6542): NoOverlayWarning successfully initialized!
08-21 00:08:17.954 I/NoOverlayWarning(6887): Cleared FLAG_WINDOW_IS_OBSCURED flag`

**Comment by daniel-lo** [comment]
@aviraxp  just sent the logfile to you too :-)

**Comment by apsun** [comment]
@daniel-lo Have you tried getting the overlay detected dialog to display? Everything in the logs looks normal.

**Comment by daniel-lo** [comment]
That's exactly what I did. I started loggin then I started Duo which complained that camera has no rights .. I then went to toggle camera rights on and I get the overlay detected dialog.

**Comment by aviraxp** [comment]
There is no Cleared FLAG_WINDOW_IS_OBSCURED flag. That means the flag=0
.
What app do you use to overlay?

**Comment by daniel-lo** [comment]
Button Saviour Pro

**Comment by daniel-lo** [comment]
I see there is an update for xposed .. I'll flash that and see if that helps

**Comment by aviraxp** [comment]
Works on my device. Strange.

**Comment by apsun** [comment]
This looks suspicious.

https://android.googlesource.com/platform/frameworks/native/+/03a53d1c7765eeb3af0bc34c3dff02ada1953fbf%5E!/

I suspect this has changed in the `com.google.android.packageinstaller` package but has not been pushed publicly.

Also interesting that everyone reporting issues is on Marshmallow (which is when this change was introduced)

**Comment by daniel-lo** [comment]
New Xposed didn't help.

**Comment by apsun** [comment]
Try this build: [NoOverlayWarning-1.2.apk.zip](https://github.com/apsun/NoOverlayWarning/files/428422/NoOverlayWarning-1.2.apk.zip)

**Comment by daniel-lo** [comment]
Is this the general hack .. or jst for the appinstaller?

**Comment by apsun** [comment]
The package installer is responsible for the "Install APK file" window and the permission request dialog in all apps. Do you need this module to work anywhere else?

**Comment by daniel-lo** [comment]
aviraxp provided me a version that was supposed to remove the security feature for good.
I constantly need it .. because I have so many apps that make me disable the overlay before I can set credentials. I moved to a new phone and of my many apps not all have been started yet.

Aktually .. Installation of APK files is not my issue at all .. this always works. The frst app run is the issue .. when the apps ask for permissions .. at least that's how I perceive it.

DUO for example installed fine .. but on first run tells me that camera needs permissions. Maybe because there was an overlay at install time .. don't know.

**Comment by daniel-lo** [comment]
This time it worked .. maybe the "Install APK file" is the one that is run every time an app asks for permissions. Quite confusing to me .. since I don't understand exactly what's going on anyway.

**Comment by aviraxp** [comment]
I will make another version for you. But since I am going out  for a few days you have to wait.

**Comment by daniel-lo** [comment]
@aviraxp  at the moment it looks to me like I was mistaken. Version 1.2 did exactly what I wanted it to do .. so I assume each permission call goes through the APK Installer. In that case I would be perfectly fine. I expected that the fix is required for each app that needs credentials.

**Comment by aviraxp** [comment]
I hold the same view.

**Comment by aviraxp** [comment]
Try this @daniel-lo https://github.com/aviraxp/NoOverlayWarning/blob/patch-2/app-release.apk

**Comment by apsun** [comment]
@aviraxp Just a heads up, your version will also disable overlay detection in e.g. SuperSU. I suggest adding this check inside of `handleLoadPackage`, for security purposes:

``` Java
if ("eu.chainfire.supersu".equals(lpparam.packageName)) {
    return;
}
```

**Comment by aviraxp** [comment]
OK. I will add it in anothe branch as someone needs to bypass supersu.

**Comment by daniel-lo** [comment]
Hah .. now that I don't get the error anymore (due to your module) .. I don't know how to test it .. but if I get it the next time .. I will gladly interrupt and try this one ;-)
